server:
  port: 8050
## Dubbo 
spring: 
  dubbo: 
    application: 
      name: senyint-springboot-dubbo-provider
    registry: 
      address: zookeeper://172.16.140.91:2181
    protocol: 
      name: dubbo
      port: 20880
    scan: com.senyint.dubbo.service
  datasource: 
    url: jdbc:mysql://localhost:3306/mapper
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    druid: 
      initial-size: 10
      min-idle: 10
      max-active: 100
      test-on-borrow: true
      stat-view-servlet.allow: true
      query-timeout: 5000
      transaction-query-timeout: 5000
      remove-abandoned-timeout: 1800

mybatis:
    type-aliases-package: com.senyint.dubbo.entity
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - com.senyint.dubbo.util.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql